set -g @plugin 'tmux-plugins/tpm'

# Themes
# Powerline
set -g @plugin 'erikw/tmux-powerline'
# set-option -g status on
# set-option -g status-interval 2
# set-option -g status-justify "centre"
# set-option -g status-left-length 91
# set-option -g status-right-length 91
# set-option -g status-left "#(~/.tmux/plugins/tmux-powerline/powerline.sh left)"
# set-option -g status-right "#(~/.tmux/plugins/tmux-powerline/powerline.sh right)"
# set-hook -g session-created 'run-shell "~/.tmux/plugins/tmux-powerline/powerline.sh init"' # prettifies the window-status segments

# Vim <-> Tmux navigation
set -g @plugin 'christoomey/vim-tmux-navigator'

set-option -g status-position top
set-option -g default-shell /bin/zsh

set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Automatic rename of window to current path
set-option -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# Scroll your way into copy mode (scrollback buffer)
# and select text for copying with the mouse
set -g mouse on

# neovim recommendations
set-option -sg escape-time 10
set-option -g focus-events on

unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# split panes using | and - and open in current dir
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Use vim keys to resize
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

bind -r m resize-pane -Z

# set vi-mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

run -b '~/.tmux/plugins/tpm/tpm'
